# -*- coding: utf-8 -*-


# 时区
TIMEZONE = "Asia/Shanghai"


# lp_steam_actual delta upper limit, t/h
# LP_STEAM_ACTUAL_DELTA_UPPER_LIMIT = 5


# read resolution
RESOLUTION_1d = "1d"
RESOLUTION_1h = "1h"
RESOLUTION_1min = "1min"
RESOLUTION_5s = "5s"

# read interval, 当前时间戳往前取 interval second 的数据，取 resolution 聚合的数据
INTERVAL_OPERATIONAL_DIRECT = 10 * 60
INTERVAL_OPERATIONAL_1h = 5 * 3600
INTERVAL_HISTORY_15min =  15 * 7 * 60
INTERVAL_OPERATIONAL_1d = 5 * 24 * 3600
INTERVAL_HISTORY_17h = 17 * 3600

# 预测模型异常处理阈值
STEAMFLOW_PRED_AVG_PRED_MEAN = 40
ELECTRICITY_POWER_PRED_AVG_PRED_MEAN = 10

# 低压蒸汽管网压力方差
LP_STEAM_PRESSURE_STD = 0.02
LP_STEAM_PRESSURE_MIN = 0       # 低压蒸汽管网压力稳态阈值最小值
LP_STEAM_PRESSURE_MAX = 0.02    # 低压蒸汽管网压力稳态阈值最大值
# LP_STEAM_PRESSURE_MAX = 0.15


# 外购电功率处理阈值
ELECTRICITY_POWER_EXT_SALE_THREAD = -0.7


# 汽轮机单次调整进汽、抽汽量
TURBINE_STEAM_ADJUST_DELTA = 20

# 汽轮发电机组停开机状态判断进汽量
ETURB_M1_MACHINE_STATUS = 10
ETURB_M2_MACHINE_STATUS = 10
BTURB_M1_MACHINE_STATUS = 10

# 锅炉参数
BOILER_NUMBER = 3             # 锅炉数量
BOILER_M1_STEAM_THRESHOLD = 3 # 1# 锅炉停机阈值，低于阈值进行停炉
BOILER_M2_STEAM_THRESHOLD = 3 # 2# 锅炉停机阈值，低于阈值进行停炉
BOILER_M3_STEAM_THRESHOLD = 3 # 1# 锅炉停机阈值，低于阈值进行停炉

# 外购电外购电峰谷平外购电峰谷平时间段时间节点
TIMEZONE_MIN_LOWER_1 = 0
TIMEZONE_MIN_UPPER_1 = 8
TIMEZONE_MID_LOWER_1 = 8
TIMEZONE_MID_UPPER_1 = 9
TIMEZONE_MID_LOWER_2 = 12
TIMEZONE_MID_UPPER_2 = 19
TIMEZONE_MID_LOWER_3 = 22
TIMEZONE_MID_UPPER_3 = 23
TIMEZONE_MAX_LOWER_1 = 9
TIMEZONE_MAX_UPPER_1 = 12
TIMEZONE_MAX_LOWER_2 = 19
TIMEZONE_MAX_UPPER_2 = 22

# 锅炉、汽轮发电机组吻合度评级分数
# GOOD_THRESHOLD = 0.8
# FINE_THRESHOLD = 0.65
# BAD_THRESHOLD = 0.5
GOOD_THRESHOLD = 4
FINE_THRESHOLD = 7
BAD_THRESHOLD = 10




# 早中晚班时间节点
MORNING_CLASS_LOWER_LIMIT = 0
MORNING_CLASS_UPPER_LIMIT = 7
MIDDLE_CLASS_LOWER_LIMIT = 8
MIDDLE_CLASS_UPPER_LIMIT = 15
NIGHT_CLASS_LOWER_LIMIT = 16
NIGHT_CLASS_UPPER_LIMIT = 23

# DM 模型触发频率时长
INVOCATION_FREQUENCY = "50s"

# 锅炉、汽机优化使用的蒸汽、电力需求量
STEAM_ELECTRICITY_RUNNING_MODE = 0

# CFBoiler 锅炉热效率模型同一条消息发送间隔
INFORMATION_INTERVAL = 5 * 60
